# Generated by Django 2.2.5 on 2020-08-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('conf_num', models.CharField(max_length=15)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='MailModel',
        ),
    ]
