# Generated by Django 2.2.5 on 2020-08-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailerApp', '0004_remove_newsletter_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='contents',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
