# Generated by Django 3.1 on 2020-08-20 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailerApp', '0006_auto_20200817_1615'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
