# Generated by Django 3.1 on 2020-08-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailerApp', '0007_delete_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_field', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='contents',
            field=models.TextField(max_length=200),
        ),
    ]
