# Generated by Django 3.1 on 2020-08-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailerApp', '0009_subscriber_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
