# Generated by Django 3.1 on 2020-08-22 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailerApp', '0010_auto_20200821_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='email',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mailerApp.subscriber'),
            preserve_default=False,
        ),
    ]
