# Generated by Django 3.1 on 2020-08-22 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailerApp', '0011_newsletter_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='email',
        ),
    ]
