# Generated by Django 3.1 on 2020-08-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailerApp', '0012_remove_newsletter_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
